server:
  port: 8080


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service-route
          uri: lb://users-service
          predicates:
            - Path=/api/auth/**
        - id: wallet-service-routes
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallet/**
          filters:
            - AuthenticationFilter
        - id: merchant-service-routes
          uri: lb://merchant-service
          predicates:
            - Path=/api/merchant/**
          filters:
            - AuthenticationFilter
        - id: payment-orchestrator-service-routes
          uri: lb://payment-orchestrator-service
          predicates:
            - Path=/api/transfer/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
